### ISSUE TITLE
Don't generate generic thumbnails

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-thumbnails#4]
Don't generate generic thumbnail for acdh:Collection/acdh:TopCollection and acdh:Resource

**Comment by sstuhec** [comment]
Thumbnail should be used for TopCollection I realize, because some TopCollections do not provide a title image and it will look very empty in the slide show on the front page, if there is nothing there.


![Image](https://github.com/acdh-oeaw/arche-thumbnails/assets/61146008/eac0adb5-c9be-4e19-a360-4816f49e5112)

**Comment by zozlak** [comment]
Implemented by 0b7988e958dff7260226aa6df8d833a283284e83 but may require some fixes on the GUI side.
